package ir.dastranj.app.data.db

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import androidx.core.content.edit
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import java.security.SecureRandom

/**
 * Supplies the SQLCipher passphrase for the database (PRD §12).
 *
 * ## Design
 *
 * SQLCipher needs a passphrase as bytes, but the Android Keystore will not hand out raw key
 * material — that is the point of it. So the scheme is the standard two-key one:
 *
 * 1. A random 32-byte **database passphrase** is generated once, on first launch.
 * 2. That passphrase is encrypted with an AES key that lives **inside** the Keystore and cannot be
 *    exported, and the ciphertext is stored in SharedPreferences.
 * 3. On later launches the ciphertext is read back and decrypted through the Keystore.
 *
 * The stored blob is therefore useless without the hardware-backed key, and the key itself never
 * leaves the secure hardware. An attacker with the app's private directory — via a backup, a rooted
 * device, or a forensic image — gets neither the database nor the passphrase.
 *
 * ## Why not EncryptedSharedPreferences
 *
 * It would do the same job, but it is a Jetpack Security dependency whose 1.x line is deprecated
 * and whose behaviour on some vendor ROMs has been unreliable. The primitive here is small enough
 * to own outright.
 *
 * ## Failure mode
 *
 * If the Keystore entry is lost — the user removes their lock screen on some OEM builds, or the app
 * is restored to a different device — the passphrase cannot be recovered and the database cannot be
 * opened. That is the intended security property, and it is consistent with PRD §16's accepted
 * consequence that v1 has no backup: the data is local, encrypted, and not recoverable elsewhere.
 */
class DatabaseKeyProvider(private val context: Context) {

    /**
     * Returns the database passphrase, creating and storing it on first call.
     *
     * Synchronised because Room may open the database from more than one thread on a cold start,
     * and two concurrent first-runs would otherwise each generate a passphrase — the loser's
     * database would then be unopenable.
     */
    @Synchronized
    fun getOrCreatePassphrase(): ByteArray {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val storedBlob = prefs.getString(KEY_ENCRYPTED_PASSPHRASE, null)

        if (storedBlob != null) {
            return decrypt(Base64.decode(storedBlob, Base64.NO_WRAP))
        }

        val passphrase = ByteArray(PASSPHRASE_BYTES).also { SecureRandom().nextBytes(it) }
        val encrypted = encrypt(passphrase)
        prefs.edit {
            putString(KEY_ENCRYPTED_PASSPHRASE, Base64.encodeToString(encrypted, Base64.NO_WRAP))
        }
        return passphrase
    }

    /**
     * Encrypts with AES-GCM and prepends the IV.
     *
     * A fresh IV per encryption is generated by the Keystore itself; reusing one with GCM would be
     * catastrophic, so it is never supplied by this code.
     */
    private fun encrypt(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKeystoreKey())
        val iv = cipher.iv
        val ciphertext = cipher.doFinal(plaintext)
        return ByteArray(1 + iv.size + ciphertext.size).also { out ->
            out[0] = iv.size.toByte()
            iv.copyInto(out, destinationOffset = 1)
            ciphertext.copyInto(out, destinationOffset = 1 + iv.size)
        }
    }

    private fun decrypt(blob: ByteArray): ByteArray {
        val ivSize = blob[0].toInt()
        val iv = blob.copyOfRange(1, 1 + ivSize)
        val ciphertext = blob.copyOfRange(1 + ivSize, blob.size)

        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            getOrCreateKeystoreKey(),
            GCMParameterSpec(GCM_TAG_BITS, iv),
        )
        return cipher.doFinal(ciphertext)
    }

    private fun getOrCreateKeystoreKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (keyStore.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(AES_KEY_BITS)
                // Deliberately NOT setUserAuthenticationRequired: the app has no lock screen of its
                // own in v1, and requiring device auth here would make the database unopenable on a
                // phone with no secure lock set.
                .setRandomizedEncryptionRequired(true)
                .build(),
        )
        return generator.generateKey()
    }

    private companion object {
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val KEY_ALIAS = "dastranj_db_key"
        const val PREFS_NAME = "dastranj_secure"
        const val KEY_ENCRYPTED_PASSPHRASE = "db_passphrase"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val GCM_TAG_BITS = 128
        const val AES_KEY_BITS = 256
        const val PASSPHRASE_BYTES = 32
    }
}
